# Generated by Django 5.0.2 on 2024-03-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Выполнено'), ('not done', 'Не выполнено')], max_length=255),
        ),
    ]
